### ISSUE TITLE
Appears not to like nested resources

### ISSUE THREAD

**Issue by cflipse** [livingsocial/swagger_yard#26]
defining for a nested controller:

```
@resource test
@resource_path /api/user/{user_id}/tests
@resource_parameter user_id [String]
class API::UserTestsController < APIController

# ....
end
```

Results in JS cratering and printing the message: 
`Unable to read api '' from path http://server/swagger/api/users/{user_id}/tests/ (server returned  undefined)`

and the JS appears to be trying to fetch the resource URL directly, escaping the braces in the URL.

**Comment by nicksieger** [comment]
Closing, as `@resource_path` is no longer used.
