### ISSUE TITLE
How do I use this gem?

### ISSUE THREAD

**Issue by LandonSchropp** [livingsocial/swagger_yard#46]
Sorry, if this is an obvious question. I followed the instructions in the readme, including adding the gem and the initializer. However, if I run `yard` I don't see any Swagger files generated. Am I missing something?

**Comment by nicksieger** [comment]
This is probably a README issue. The getting started instructions could use some love. 

This library provides the YARD custom tags and code to build a swagger spec from the tags in your source code, but no actual code or routines to output it. For example, [this file in swagger_yard-rails](https://github.com/livingsocial/swagger_yard-rails/blob/master/lib/swagger_yard/rails/tasks.rake) has a rake task for outputting the swagger spec as a JSON file.

Another way to answer the question is that you probably want to also use `swagger_yard-rails`. Does that help?

**Comment by LandonSchropp** [comment]
Yep, that solved my problem. Thank you!
